= 밥상일터 API
:doctype: book
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:seclinks:

== 회원관리 API (MemberController)
=== 회원가입 성공 API
==== 요청
operation::member-controller-test/join-test[snippets="http-request,request-fields"]
==== 응답
operation::member-controller-test/join-test[snippets="http-response,response-fields"]
=== 회원가입 실패 API
==== 요청
operation::member-controller-test/join-fail-test[snippets="http-request,request-fields"]
==== 응답
operation::member-controller-test/join-fail-test[snippets="http-response,response-fields"]
=== 회원 상세정보 입력 성공 API
==== 요청
operation::member-controller-test/add-detail-test[snippets="http-request,request-fields"]
==== 응답
operation::member-controller-test/add-detail-test[snippets="http-response,response-fields"]
=== 회원 상세정보 입력 실패 API
==== 요청
operation::member-controller-test/add-detail-fail-test[snippets="http-request,request-fields"]
==== 응답
operation::member-controller-test/add-detail-fail-test[snippets="http-response,response-fields"]

== 식당 API (RestaurantController)
=== 식당 리스트 요청 API
==== 요청
operation::restaurant-controller-test/find-all-by-page[snippets="http-request,query-parameters"]
==== 응답
operation::restaurant-controller-test/find-all-by-page[snippets="http-response,response-fields"]
=== 식당 상세조회 API
==== 요청
operation::restaurant-controller-test/find-detail[snippets="http-request,path-parameters"]
==== 응답
operation::restaurant-controller-test/find-detail[snippets="http-response,response-fields"]
=== 식당 상세조회 실패 API
==== 요청
operation::restaurant-controller-test/find-detail-fail[snippets="http-request,path-parameters"]
==== 응답
operation::restaurant-controller-test/find-detail-fail[snippets="http-response,response-fields"]

== 크레딧 API (CreditController)
=== 회원의 크레딧 정보 요청 API
==== 요청
operation::credit-controller-test/find-credit-test[snippets="http-request,path-parameters"]
==== 응답
operation::credit-controller-test/find-credit-test[snippets="http-response,response-fields"]
=== 크레딧 증가 API
==== 요청
operation::credit-controller-test/plus-credit-test[snippets="http-request,request-fields"]
==== 응답
operation::credit-controller-test/plus-credit-test[snippets="http-response,response-fields"]
=== 크레딧 감소 API
==== 요청
operation::credit-controller-test/minus-credit-test[snippets="http-request,request-fields"]
==== 응답
operation::credit-controller-test/minus-credit-test[snippets="http-response,response-fields"]

== 소일거리 API (WorkController)
=== 소일거리 리스트 요청 API
==== 요청
operation::work-controller-test/find-all-test[snippets="http-request,query-parameters"]
==== 응답
operation::work-controller-test/find-all-test[snippets="http-response,response-fields"]
=== 소일거리 상세조회 API
==== 요청
operation::work-controller-test/find-by-id-test[snippets="http-request,path-parameters"]
==== 응답
operation::work-controller-test/find-by-id-test[snippets="http-response,response-fields"]
=== 소일거리 참가 API
==== 요청
operation::work-controller-test/join-work-test[snippets="http-request,request-fields"]
==== 응답
operation::work-controller-test/join-work-test[snippets="http-response,response-fields"]
